api_header: /u/SerpentineLogic  Eve Online universe news poster v0.1.5
subreddit: new_eden_news_bot
username: new_eden_news_bot
password: insert_password_here
signature: ''
sleep_time: 300
sleep_time_post: 300
submitpost: true
